POST http://localhost:7071/api/Products

{
    "product":{
        "Id": "e77344a9-1e81-4362-afca-520a5bd826f8",
        "Reference": "abc",
        "Desc": "Produto Novo",
        "Price": 12
    }
}