POST http://localhost:7071/api/Products

{
    "product":{
        "Reference": "TENIS01",
        "Desc": "TENIS NIKE 40",
        "Category": "SHOES",
        "Quantidade": 10,
        "Price": 13.50
    }
}